services:
  - type: web
    name: tours-regions-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 18
