export const placesList: Record<string, string[]> = {
  "Andhra Pradesh": ["Tirumala Venkateswara Temple", "Borra Caves", "Araku Valley", "Rishikonda Beach", "Undavalli Caves", "Kailasagiri", "Simhachalam Temple", "Belum Caves", "Lepakshi", "Amaravati Stupa"],
  "Arunachal Pradesh": ["Tawang Monastery", "Ziro Valley", "Sela Pass", "Namdapha National Park", "Bomdila Monastery", "Dirang Valley", "Pankang Teng Tso Lake", "Madhuri Lake", "Itanagar Fort", "Mehao Wildlife Sanctuary"],
  "Assam": ["Kaziranga National Park", "Kamakhya Temple", "Majuli Island", "Manas National Park", "Umananda Temple", "Kakochang Waterfalls", "Pobitora Wildlife Sanctuary", "Dibru-Saikhowa National Park", "Agnigarh", "Haflong Hill"],
  "Bihar": ["Mahabodhi Temple", "Nalanda University Ruins", "Gaya", "Vishnupad Temple", "Vikramshila Ruins", "Rajgir Hot Springs", "Griddhakuta Peak", "Jalmandir", "Golghar", "Barabar Caves"],
  "Chhattisgarh": ["Chitrakote Waterfalls", "Bhoramdeo Temple", "Sirpur", "Kanger Valley National Park", "Tirathgarh Falls", "Maitri Bagh", "Mainpat", "Dongargarh", "Rajim", "Kailash and Kutumsar Caves"],
  "Goa": ["Basilica of Bom Jesus", "Dudhsagar Falls", "Palolem Beach", "Baga Beach", "Aguada Fort", "Anjuna Beach", "Chapora Fort", "Vagator Beach", "Se Cathedral", "Mangueshi Temple"],
  "Gujarat": ["Statue of Unity", "Gir National Park", "Rann of Kutch", "Somnath Temple", "Dwarkadhish Temple", "Sabarmati Ashram", "Sun Temple, Modhera", "Rani ki Vav", "Laxmi Vilas Palace", "Akshardham Temple"],
  "Haryana": ["Brahma Sarovar", "Sultanpur National Park", "Pinjore Gardens", "Kurukshetra Panorama", "Surajkund", "Morni Hills", "Badkhal Lake", "Tilyar Lake", "Bhindawas Bird Sanctuary", "Sheikh Chilli Tomb"],
  "Himachal Pradesh": ["Rohtang Pass", "Shimla Ridge", "Spiti Valley", "Solang Valley", "Hidimba Devi Temple", "Dalhousie", "Khajjiar", "Dharamshala", "Triund", "Kinnaur"],
  "Jharkhand": ["Baidyanath Temple", "Hundru Falls", "Betla National Park", "Dassam Falls", "Jonha Falls", "Jagannath Temple Ranchi", "Pahari Mandir", "Dalma Wildlife Sanctuary", "Jubilee Park", "Parasnath Hill"],
  "Karnataka": ["Mysore Palace", "Hampi Monuments", "Coorg", "Gokarna", "Jog Falls", "Bandipur National Park", "Lalbagh Botanical Garden", "Pattadakal", "Chikmagalur", "Badami Caves"],
  "Kerala": ["Munnar", "Alleppey Backwaters", "Wayanad", "Padmanabhaswamy Temple", "Kochi Fort", "Thekkady", "Varkala Beach", "Athirappilly Waterfalls", "Kumarakom Bird Sanctuary", "Bekal Fort"],
  "Madhya Pradesh": ["Khajuraho Temples", "Sanchi Stupa", "Bandhavgarh National Park", "Gwalior Fort", "Kanha National Park", "Bhedaghat", "Ujjain Mahakaleshwar", "Pachmarhi", "Bhimbetka Rock Shelters", "Mandu"],
  "Maharashtra": ["Gateway of India", "Ajanta and Ellora Caves", "Mahabaleshwar", "Lonavala", "Elephanta Caves", "Shirdi", "Tadoba Andhari Tiger Reserve", "Panchgani", "Pratapgad Fort", "Marine Drive"],
  "Manipur": ["Loktak Lake", "Kangla Fort", "Keibul Lamjao National Park", "Shree Govindajee Temple", "INA Memorial", "Khongjom War Memorial", "Sadu Chiru Waterfall", "Dzukou Valley (Manipur side)", "Manipur State Museum", "Khangkhui Cave"],
  "Meghalaya": ["Living Root Bridges", "Nohkalikai Falls", "Mawlynnong Village", "Umiam Lake", "Elephant Falls", "Dawki River", "Shillong Peak", "Laitlum Canyons", "Mawsmai Cave", "Cherrapunji"],
  "Mizoram": ["Phawngpui", "Vantawng Falls", "Reiek Tlang", "Solomon's Temple", "Durtlang Hills", "Falkawn Village", "Tam Dil Lake", "Mizoram State Museum", "Lushai Hills", "Murlen National Park"],
  "Nagaland": ["Dzukou Valley", "Kisama Heritage Village", "Japfu Peak", "Kachari Ruins", "Shilloi Lake", "Kohima War Cemetery", "Mokokchung", "Tuophema Village", "Intanki National Park", "Mount Saramati"],
  "Odisha": ["Konark Sun Temple", "Jagannath Temple", "Chilika Lake", "Lingaraja Temple", "Udayagiri and Khandagiri Caves", "Dhauli Shanti Stupa", "Simlipal National Park", "Bhitarkanika National Park", "Cuttack Chandi Temple", "Chandipur Beach"],
  "Punjab": ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Anandpur Sahib", "Qila Mubarak", "Virasat-e-Khalsa", "Sheesh Mahal", "Moti Bagh Palace", "Akal Takht", "Gobindgarh Fort"],
  "Rajasthan": ["Hawa Mahal", "Mehrangarh Fort", "Udaipur City Palace", "Amer Fort", "Jaisalmer Fort", "Ranthambore National Park", "Pushkar Lake", "Jantar Mantar", "Lake Pichola", "Chittorgarh Fort"],
  "Sikkim": ["Nathu La", "Rumtek Monastery", "Gurudongmar Lake", "Tsomgo Lake", "Pelling", "Yumthang Valley", "Namchi", "Ravangla", "Zuluk", "Kanchenjunga National Park"],
  "Tamil Nadu": ["Meenakshi Temple", "Brihadisvara Temple", "Marina Beach", "Ooty", "Rameswaram Temple", "Kanyakumari", "Mahabalipuram", "Kodaikanal", "Mudumalai National Park", "Vivekananda Rock Memorial"],
  "Telangana": ["Charminar", "Golconda Fort", "Ramappa Temple", "Hussain Sagar", "Salar Jung Museum", "Chowmahalla Palace", "Warangal Fort", "Thousand Pillar Temple", "Bhongir Fort", "Nehru Zoological Park"],
  "Tripura": ["Neermahal", "Ujjayanta Palace", "Unakoti", "Tripura Sundari Temple", "Sepahijala Wildlife Sanctuary", "Jampui Hill", "Heritage Park", "Pilak", "Deotamura", "Dumboor Lake"],
  "Uttar Pradesh": ["Taj Mahal", "Varanasi Ghats", "Fatehpur Sikri", "Agra Fort", "Kashi Vishwanath Temple", "Sarnath", "Ram Janmabhoomi", "Bara Imambara", "Triveni Sangam", "Dudhwa National Park"],
  "Uttarakhand": ["Badrinath Temple", "Valley of Flowers", "Nainital Lake", "Kedarnath Temple", "Rishikesh", "Har Ki Pauri", "Jim Corbett National Park", "Mussoorie", "Auli", "Gangotri Temple"],
  "West Bengal": ["Victoria Memorial", "Sundarbans National Park", "Darjeeling Himalayan Railway", "Howrah Bridge", "Dakshineswar Kali Temple", "Belur Math", "Digha Beach", "Hazarduari Palace", "Indian Museum", "Tiger Hill"],

  // Union Territories
  "Andaman and Nicobar Islands": ["Cellular Jail", "Radhanagar Beach", "Ross Island", "Havelock Island", "Baratang Island", "Neil Island", "Mahatma Gandhi Marine National Park", "Chidiya Tapu", "Viper Island", "Mount Harriet"],
  "Chandigarh": ["Rock Garden of Chandigarh", "Sukhna Lake", "Rose Garden", "Capitol Complex", "Pinjore Gardens", "Government Museum and Art Gallery", "Le Corbusier Centre", "ChattBir Zoo", "Japanese Garden", "Terraced Garden"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Diu Fort", "Vanganga Lake Garden", "Nagoa Beach", "Gangeshwar Mahadev Temple", "St. Paul's Church", "Naida Caves", "Devka Beach", "Jampore Beach", "Silvassa Vasona Lion Safari", "Swaminarayan Temple"],
  "Delhi": ["Red Fort", "Qutub Minar", "India Gate", "Humayun's Tomb", "Lotus Temple", "Akshardham Temple", "Jama Masjid", "Jantar Mantar", "Lodhi Garden", "Chandni Chowk"],
  "Jammu and Kashmir": ["Dal Lake", "Gulmarg Gondola", "Vaishno Devi Temple", "Pahalgam", "Shankaracharya Temple", "Sonamarg", "Mughal Gardens", "Amarnath Cave", "Betaab Valley", "Apharwat Peak"],
  "Lakshadweep": ["Agatti Island", "Minicoy Island", "Bangaram Atoll", "Kavaratti Island Marine Aquarium", "Kalpeni Island", "Kadmat Island", "Thinnakara Island", "Pitti Bird Sanctuary", "Amini Beach", "Andrott Island"],
  "Ladakh": ["Pangong Tso", "Nubra Valley", "Thiksey Monastery", "Magnetic Hill", "Shanti Stupa", "Khardung La", "Tso Moriri", "Leh Palace", "Hemis Monastery", "Diskit Monastery"],
  "Puducherry": ["Auroville", "Promenade Beach", "Sri Aurobindo Ashram", "Paradise Beach", "Basilica of the Sacred Heart", "Auroville Beach", "Serenity Beach", "Botanical Garden", "Ousteri Lake", "French War Memorial"]
};
